Get projects from memsource with paginated response, added all pages
ansible/python-memsource pull request #5
Opened 2022-06-02 17:59 UTC by adityamulik

Initially, the response was giving output for only 1 page of all the projects, now have added to get a list of all projects from all the pages of totalPages of the paginated API response.

2022-06-14 12:24 UTC, adityamulik commented
@Spredzy I've updated the pre-translate flag and updated the requests.post() method to push any binary file to memsource (e.g. json file upload to memsource).

2022-06-14 14:12 UTC, rooftopcellist commented on memsource/__init__.py
> -            'Content-type': 'application/octet-stream',
@adityamulik found that a binary stream does not work for json data, but not specifying the content type header works as expected.

2022-06-14 14:18 UTC, rooftopcellist approved these changes

2022-06-16 12:44 UTC, Spredzy commented on memsource/__init__.py
> +            return requests.post(url, headers=headers, data=files).json() # Bug fix to push json files
@adityamulik is there a reason `self.handle_rest_call` couldn't be used here ? Could you expand it (if need be) so it supports what you are trying to do ?

2022-06-16 12:44 UTC, Spredzy commented on memsource/__init__.py
> +        headers.update({"Authorization": "ApiToken %s" % self.auth.token})
This should be handled by `self.handle_rest_call()` IIRC

2022-06-16 12:46 UTC, Spredzy commented on memsource/__init__.py
> +        kwargs.update({'preTranslate': preTranslate})
nit: You chould used the above update and just expand on the dict.

Currently you have:

```
kwargs.update({'targetLangs': langs})
kwargs.update({'preTranslate': preTranslate})
```

You could go

```
kwargs.update({
    'targetLangs': langs.
    'preTranslate': preTranslate
})
```

2022-06-16 12:46 UTC, Spredzy requested changes
Some inner comments before merging

2022-06-16 14:14 UTC, adityamulik commented on memsource/__init__.py
> +        kwargs.update({'preTranslate': preTranslate})
Updated the kwargs as per above.

2022-06-16 14:57 UTC, rooftopcellist commented on memsource/__init__.py
> +            total_pages = self.handle_rest_call(url, "GET").json()["totalPages"]
Passing thought, if we end up having more instances where we need to get all pages, maybe we could make this a separate function that takes URL path as an argument and returns the content of all pages.

2022-06-17 09:56 UTC, Spredzy approved these changes

2022-06-17 09:56 UTC, merged